query_table = query_table.append(df.query('borough == ["Manhattan"]'))
# plt.scatter(query_table.temp.values, query_table.pickups.values, alpha=0.1, color="blue", label='Manhattan', edgecolors='blue')
# z = np.polyfit(query_table.temp.values, query_table.pickups.values, 1)
# p = np.poly1d(z)
# plt.plot(query_table.temp.values, p(query_table.temp.values),"k--") 

# query_table = query_table.append(df.query('borough == ["Bronx"]'))
# plt.scatter(query_table.temp.values, query_table.pickups.values, alpha=1, color='red', label='Bronx', edgecolors='grey')
# z = np.polyfit(query_table.temp.values, query_table.pickups.values, 1)
# p = np.poly1d(z)
# plt.plot(query_table.temp.values, p(query_table.temp.values),"k--")

# query_table = query_table.append(df.query('borough == ["Brooklyn"]'))
# plt.scatter(query_table.temp.values, query_table.pickups.values, alpha=1, color='yellow', label='Brooklyn', edgecolors='grey')
# z = np.polyfit(query_table.temp.values, query_table.pickups.values, 1)
# p = np.poly1d(z)
# plt.plot(query_table.temp.values, p(query_table.temp.values),"k--")

# query_table = query_table.append(df.query('borough == ["EWR"]'))
# plt.scatter(query_table.temp.values, query_table.pickups.values, alpha=1, color='green', label='EWR', edgecolors='grey')
# z = np.polyfit(query_table.temp.values, query_table.pickups.values, 1)
# p = np.poly1d(z)
# plt.plot(query_table.temp.values, p(query_table.temp.values),"k--")

# query_table = query_table.append(df.query('borough == ["Queens"]'))
# plt.scatter(query_table.temp.values, query_table.pickups.values, alpha=1, color='purple', label='Queens', edgecolors='grey')
# z = np.polyfit(query_table.temp.values, query_table.pickups.values, 1)
# p = np.poly1d(z)
# plt.plot(query_table.temp.values, p(query_table.temp.values),"k--")